# Generated by Django 3.0.1 on 2019-12-22 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0003_auto_20191221_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_leads', to=settings.AUTH_USER_MODEL),
        ),
    ]
